=== mmi-ing/Java_World/Ex1114/src/ex5.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT root (person+)>
<!-- 
	* : 생략 가능, 중복 가능
	+ : 생략 불가능, 중복 가능
	? : 생략 가능, 중복 불가능
-->
<!ELEMENT person (name, age, phone*, email?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ATTLIST person no CDATA #FIXED "A10">
<!ATTLIST phone 통신사 CDATA #REQUIRED>
<!-- 
	위는 person요소에 no라는 속성을 설정한 것이다.
	만약! person요소에 no라는 속성을 정의한다면
	반드시 속성의 값이 "A10"이어야 한다.
	phone요소에는 통신사라는 속성이 반드시 정의해야 한다. 
	-->

=== mmi-ing/Java_World/Ex1114/src/ex5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 외부의 DTD를 참조한다. -->
<!DOCTYPE root SYSTEM "ex5.dtd">
<root>
	<person>
		<name>마루치</name>
		<age>20</age>
		<phone 통신사="SKT">010</phone>
		<email>maru@korea.com</email>
	</person>
	<person>
		<name>아라치</name>
		<age>21</age>
		<phone 통신사="SKT">010</phone>
		<phone 통신사="SKT">010</phone>
	</person>
</root>
